<?php
/**
 * CardsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RestyaBoard
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CardsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CardsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1BoardsBoardIdCardsJsonDelete
     *
     * Deletes a cards.
     *
     */
    public function testV1BoardsBoardIdCardsJsonDelete()
    {
    }

    /**
     * Test case for v1BoardsBoardIdCardsSearchJsonGet
     *
     * cards by name.
     *
     */
    public function testV1BoardsBoardIdCardsSearchJsonGet()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdCardsCardIdActivitiesJsonGet
     *
     * Activities.
     *
     */
    public function testV1BoardsBoardIdListsListIdCardsCardIdActivitiesJsonGet()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdCardsCardIdAttachmentsAttachmentIdJsonDelete
     *
     * Remove attachment from card.
     *
     */
    public function testV1BoardsBoardIdListsListIdCardsCardIdAttachmentsAttachmentIdJsonDelete()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdCardsCardIdCardSubscribersJsonPost
     *
     * Subscribe Card.
     *
     */
    public function testV1BoardsBoardIdListsListIdCardsCardIdCardSubscribersJsonPost()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdCardsCardIdChecklistsCheckListIdItemsItemIdConvertToCardJsonPost
     *
     * Convert item to card.
     *
     */
    public function testV1BoardsBoardIdListsListIdCardsCardIdChecklistsCheckListIdItemsItemIdConvertToCardJsonPost()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdCardsCardIdCopyJsonPost
     *
     * Copy card.
     *
     */
    public function testV1BoardsBoardIdListsListIdCardsCardIdCopyJsonPost()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdCardsCardIdJsonDelete
     *
     * Deletes the card.
     *
     */
    public function testV1BoardsBoardIdListsListIdCardsCardIdJsonDelete()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdCardsCardIdJsonGet
     *
     * Cards.
     *
     */
    public function testV1BoardsBoardIdListsListIdCardsCardIdJsonGet()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdCardsCardIdJsonPut
     *
     * Edit card.
     *
     */
    public function testV1BoardsBoardIdListsListIdCardsCardIdJsonPut()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdCardsCardIdSearchJsonGet
     *
     * cards by listID.
     *
     */
    public function testV1BoardsBoardIdListsListIdCardsCardIdSearchJsonGet()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdCardsCardIdUsersUserIdJsonDelete
     *
     * Deletes a cardUser.
     *
     */
    public function testV1BoardsBoardIdListsListIdCardsCardIdUsersUserIdJsonDelete()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdCardsCardIdUsersUserIdJsonPost
     *
     * Assign member to card.
     *
     */
    public function testV1BoardsBoardIdListsListIdCardsCardIdUsersUserIdJsonPost()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdCardsJsonGet
     *
     * View list cards of the board.
     *
     */
    public function testV1BoardsBoardIdListsListIdCardsJsonGet()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdCardsJsonPost
     *
     * Add a new card.
     *
     */
    public function testV1BoardsBoardIdListsListIdCardsJsonPost()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdCardsJsonPut
     *
     * Move list cards.
     *
     */
    public function testV1BoardsBoardIdListsListIdCardsJsonPut()
    {
    }

    /**
     * Test case for v1UsersUserIdCardsJsonGet
     *
     * View user cards.
     *
     */
    public function testV1UsersUserIdCardsJsonGet()
    {
    }
}
