<?php
/**
 * GroupsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RestyaBoard
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * GroupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GroupsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1GroupsGroupIdJsonDelete
     *
     * delete groups.
     *
     */
    public function testV1GroupsGroupIdJsonDelete()
    {
    }

    /**
     * Test case for v1GroupsGroupIdJsonGet
     *
     * Put groups.
     *
     */
    public function testV1GroupsGroupIdJsonGet()
    {
    }

    /**
     * Test case for v1GroupsGroupIdJsonPut
     *
     * Put groups.
     *
     */
    public function testV1GroupsGroupIdJsonPut()
    {
    }

    /**
     * Test case for v1GroupsGroupIdUsersUserIdJsonDelete
     *
     * Put groups.
     *
     */
    public function testV1GroupsGroupIdUsersUserIdJsonDelete()
    {
    }

    /**
     * Test case for v1GroupsJsonGet
     *
     * Add a new groups to the card.
     *
     */
    public function testV1GroupsJsonGet()
    {
    }

    /**
     * Test case for v1GroupsJsonPost
     *
     * Add a new groups to the card.
     *
     */
    public function testV1GroupsJsonPost()
    {
    }

    /**
     * Test case for v1GroupsUsersJsonPost
     *
     * View groups_users.
     *
     */
    public function testV1GroupsUsersJsonPost()
    {
    }
}
