<?php
/**
 * ListsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RestyaBoard
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ListsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ListsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsJsonDelete
     *
     * Deletes a list.
     *
     */
    public function testV1BoardsBoardIdListsJsonDelete()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsJsonGet
     *
     * View board by ID.
     *
     */
    public function testV1BoardsBoardIdListsJsonGet()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsJsonPost
     *
     * Add a new list to the board.
     *
     */
    public function testV1BoardsBoardIdListsJsonPost()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdActivitiesJsonGet
     *
     * Activities.
     *
     */
    public function testV1BoardsBoardIdListsListIdActivitiesJsonGet()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdJsonDelete
     *
     * Deletes a list.
     *
     */
    public function testV1BoardsBoardIdListsListIdJsonDelete()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdJsonPut
     *
     * Update an existing webhooks.
     *
     */
    public function testV1BoardsBoardIdListsListIdJsonPut()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdListSubscribersJsonPost
     *
     * Add a new list subcriber to the board.
     *
     */
    public function testV1BoardsBoardIdListsListIdListSubscribersJsonPost()
    {
    }

    /**
     * Test case for v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPut
     *
     * Update an existing webhooks.
     *
     */
    public function testV1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPut()
    {
    }
}
