<?php
/**
 * OauthClientsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RestyaBoard
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * OauthClientsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OauthClientsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1OauthClientsClientIdJsonDelete
     *
     * Deletes a client.
     *
     */
    public function testV1OauthClientsClientIdJsonDelete()
    {
    }

    /**
     * Test case for v1OauthClientsClientIdJsonPut
     *
     * Update an existing Client.
     *
     */
    public function testV1OauthClientsClientIdJsonPut()
    {
    }

    /**
     * Test case for v1OauthClientsJsonGet
     *
     * Finds organizations by tags.
     *
     */
    public function testV1OauthClientsJsonGet()
    {
    }

    /**
     * Test case for v1OauthClientsJsonPost
     *
     * Add a new oauth_clients to the store.
     *
     */
    public function testV1OauthClientsJsonPost()
    {
    }
}
