<?php
/**
 * PagesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RestyaBoard
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * PagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PagesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1PagesJsonGet
     *
     * Add a new pages.
     *
     */
    public function testV1PagesJsonGet()
    {
    }

    /**
     * Test case for v1PagesJsonPost
     *
     * Add a new pages.
     *
     */
    public function testV1PagesJsonPost()
    {
    }

    /**
     * Test case for v1PagesPagesIdJsonDelete
     *
     * delete pages.
     *
     */
    public function testV1PagesPagesIdJsonDelete()
    {
    }

    /**
     * Test case for v1PagesPagesIdJsonGet
     *
     * Put pages.
     *
     */
    public function testV1PagesPagesIdJsonGet()
    {
    }

    /**
     * Test case for v1PagesPagesIdJsonPut
     *
     * Put pages.
     *
     */
    public function testV1PagesPagesIdJsonPut()
    {
    }
}
