<?php
/**
 * SalesforceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RestyaBoard
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SalesforceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SalesforceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1SalesforceJsonGet
     *
     * Add a new salesforce.
     *
     */
    public function testV1SalesforceJsonGet()
    {
    }

    /**
     * Test case for v1SalesforceJsonPost
     *
     * Add a new salesforce.
     *
     */
    public function testV1SalesforceJsonPost()
    {
    }

    /**
     * Test case for v1SalesforceSalesforceIdJsonDelete
     *
     * delete salesforce.
     *
     */
    public function testV1SalesforceSalesforceIdJsonDelete()
    {
    }

    /**
     * Test case for v1SalesforceSalesforceIdJsonGet
     *
     * Put salesforce.
     *
     */
    public function testV1SalesforceSalesforceIdJsonGet()
    {
    }

    /**
     * Test case for v1SalesforceSalesforceIdJsonPut
     *
     * Put salesforce.
     *
     */
    public function testV1SalesforceSalesforceIdJsonPut()
    {
    }
}
