<?php
/**
 * UsersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RestyaBoard
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * UsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UsersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1OauthJsonGet
     *
     * Get Oauth token.
     *
     */
    public function testV1OauthJsonGet()
    {
    }

    /**
     * Test case for v1OauthTokenJsonPost
     *
     * Get token.
     *
     */
    public function testV1OauthTokenJsonPost()
    {
    }

    /**
     * Test case for v1UsersBulkActionJsonPost
     *
     * Enter your Email, and we will send resetting your password..
     *
     */
    public function testV1UsersBulkActionJsonPost()
    {
    }

    /**
     * Test case for v1UsersForgotpasswordJsonPost
     *
     * Enter your Email, and we will send resetting your password..
     *
     */
    public function testV1UsersForgotpasswordJsonPost()
    {
    }

    /**
     * Test case for v1UsersImportJsonPost
     *
     * Import Users.
     *
     */
    public function testV1UsersImportJsonPost()
    {
    }

    /**
     * Test case for v1UsersJsonGet
     *
     * users.
     *
     */
    public function testV1UsersJsonGet()
    {
    }

    /**
     * Test case for v1UsersJsonPost
     *
     * Creates User.
     *
     */
    public function testV1UsersJsonPost()
    {
    }

    /**
     * Test case for v1UsersLoginJsonPost
     *
     * Logs user into the system.
     *
     */
    public function testV1UsersLoginJsonPost()
    {
    }

    /**
     * Test case for v1UsersLogoutJsonGet
     *
     * Logs out current logged in user session.
     *
     */
    public function testV1UsersLogoutJsonGet()
    {
    }

    /**
     * Test case for v1UsersMeJsonGet
     *
     * Fetch user.
     *
     */
    public function testV1UsersMeJsonGet()
    {
    }

    /**
     * Test case for v1UsersRegisterJsonPost
     *
     * Creates User.
     *
     */
    public function testV1UsersRegisterJsonPost()
    {
    }

    /**
     * Test case for v1UsersSearchJsonGet
     *
     * Get User by Name.
     *
     */
    public function testV1UsersSearchJsonGet()
    {
    }

    /**
     * Test case for v1UsersUserIdActivationJsonPut
     *
     * User activation.
     *
     */
    public function testV1UsersUserIdActivationJsonPut()
    {
    }

    /**
     * Test case for v1UsersUserIdActivitiesJsonGet
     *
     * Activities.
     *
     */
    public function testV1UsersUserIdActivitiesJsonGet()
    {
    }

    /**
     * Test case for v1UsersUserIdAdminchangepasswordJsonPost
     *
     * Change password.
     *
     */
    public function testV1UsersUserIdAdminchangepasswordJsonPost()
    {
    }

    /**
     * Test case for v1UsersUserIdChangepasswordJsonPost
     *
     * Edit user.
     *
     */
    public function testV1UsersUserIdChangepasswordJsonPost()
    {
    }

    /**
     * Test case for v1UsersUserIdJsonDelete
     *
     * Deletes the user.
     *
     */
    public function testV1UsersUserIdJsonDelete()
    {
    }

    /**
     * Test case for v1UsersUserIdJsonGet
     *
     * users.
     *
     */
    public function testV1UsersUserIdJsonGet()
    {
    }

    /**
     * Test case for v1UsersUserIdJsonPut
     *
     * Edit user.
     *
     */
    public function testV1UsersUserIdJsonPut()
    {
    }
}
