<?php
/**
 * Body32Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RestyaBoard
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * Body32Test Class Doc Comment
 *
 * @category    Class
 * @description Body32
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Body32Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Body32"
     */
    public function testBody32()
    {
    }

    /**
     * Test attribute "copied_card_id"
     */
    public function testPropertyCopiedCardId()
    {
    }

    /**
     * Test attribute "keep_activities"
     */
    public function testPropertyKeepActivities()
    {
    }

    /**
     * Test attribute "keep_attachments"
     */
    public function testPropertyKeepAttachments()
    {
    }

    /**
     * Test attribute "keep_checklists"
     */
    public function testPropertyKeepChecklists()
    {
    }

    /**
     * Test attribute "keep_labels"
     */
    public function testPropertyKeepLabels()
    {
    }

    /**
     * Test attribute "keep_users"
     */
    public function testPropertyKeepUsers()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }
}
