<?php
/**
 * V1customFieldsupdatePositionJsonCustomFieldTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RestyaBoard
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V1customFieldsupdatePositionJsonCustomFieldTest Class Doc Comment
 *
 * @category    Class
 * @description V1customFieldsupdatePositionJsonCustomField
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V1customFieldsupdatePositionJsonCustomFieldTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "V1customFieldsupdatePositionJsonCustomField"
     */
    public function testV1customFieldsupdatePositionJsonCustomField()
    {
    }

    /**
     * Test attribute "custom_field_id"
     */
    public function testPropertyCustomFieldId()
    {
    }

    /**
     * Test attribute "position"
     */
    public function testPropertyPosition()
    {
    }
}
