<?php
/**
 * CardVotersApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RestyaBoard
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * CardVotersApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CardVotersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDelete
     *
     * Deletes a cardVoter
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id boardId to delete (required)
     * @param  int $list_id listId to delete (required)
     * @param  int $card_id cardId to delete (required)
     * @param  int $card_voter_id cardVoterId to delete (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDelete($token, $board_id, $list_id, $card_id, $card_voter_id)
    {
        list($response) = $this->v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDeleteWithHttpInfo($token, $board_id, $list_id, $card_id, $card_voter_id);
        return $response;
    }

    /**
     * Operation v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDeleteWithHttpInfo
     *
     * Deletes a cardVoter
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id boardId to delete (required)
     * @param  int $list_id listId to delete (required)
     * @param  int $card_id cardId to delete (required)
     * @param  int $card_voter_id cardVoterId to delete (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDeleteWithHttpInfo($token, $board_id, $list_id, $card_id, $card_voter_id)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDeleteRequest($token, $board_id, $list_id, $card_id, $card_voter_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDeleteAsync
     *
     * Deletes a cardVoter
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id boardId to delete (required)
     * @param  int $list_id listId to delete (required)
     * @param  int $card_id cardId to delete (required)
     * @param  int $card_voter_id cardVoterId to delete (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDeleteAsync($token, $board_id, $list_id, $card_id, $card_voter_id)
    {
        return $this->v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDeleteAsyncWithHttpInfo($token, $board_id, $list_id, $card_id, $card_voter_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDeleteAsyncWithHttpInfo
     *
     * Deletes a cardVoter
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id boardId to delete (required)
     * @param  int $list_id listId to delete (required)
     * @param  int $card_id cardId to delete (required)
     * @param  int $card_voter_id cardVoterId to delete (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDeleteAsyncWithHttpInfo($token, $board_id, $list_id, $card_id, $card_voter_id)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDeleteRequest($token, $board_id, $list_id, $card_id, $card_voter_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDelete'
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id boardId to delete (required)
     * @param  int $list_id listId to delete (required)
     * @param  int $card_id cardId to delete (required)
     * @param  int $card_voter_id cardVoterId to delete (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDeleteRequest($token, $board_id, $list_id, $card_id, $card_voter_id)
    {
        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDelete'
            );
        }
        // verify the required parameter 'board_id' is set
        if ($board_id === null || (is_array($board_id) && count($board_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $board_id when calling v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDelete'
            );
        }
        // verify the required parameter 'list_id' is set
        if ($list_id === null || (is_array($list_id) && count($list_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $list_id when calling v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDelete'
            );
        }
        // verify the required parameter 'card_id' is set
        if ($card_id === null || (is_array($card_id) && count($card_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $card_id when calling v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDelete'
            );
        }
        // verify the required parameter 'card_voter_id' is set
        if ($card_voter_id === null || (is_array($card_voter_id) && count($card_voter_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $card_voter_id when calling v1BoardsBoardIdListsListIdCardsCardIdCardVotersCardVoterIdJsonDelete'
            );
        }

        $resourcePath = '/v1/boards/{boardId}/lists/{listId}/cards/{cardId}/card_voters/{cardVoterId}.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($token !== null) {
            $queryParams['token'] = ObjectSerializer::toQueryValue($token);
        }

        // path params
        if ($board_id !== null) {
            $resourcePath = str_replace(
                '{' . 'boardId' . '}',
                ObjectSerializer::toPathValue($board_id),
                $resourcePath
            );
        }
        // path params
        if ($list_id !== null) {
            $resourcePath = str_replace(
                '{' . 'listId' . '}',
                ObjectSerializer::toPathValue($list_id),
                $resourcePath
            );
        }
        // path params
        if ($card_id !== null) {
            $resourcePath = str_replace(
                '{' . 'cardId' . '}',
                ObjectSerializer::toPathValue($card_id),
                $resourcePath
            );
        }
        // path params
        if ($card_voter_id !== null) {
            $resourcePath = str_replace(
                '{' . 'cardVoterId' . '}',
                ObjectSerializer::toPathValue($card_voter_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPost
     *
     * Add a new card_voters
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  int $list_id Selected list ID (required)
     * @param  int $card_id Selected card ID (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPost($token, $board_id, $list_id, $card_id)
    {
        list($response) = $this->v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPostWithHttpInfo($token, $board_id, $list_id, $card_id);
        return $response;
    }

    /**
     * Operation v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPostWithHttpInfo
     *
     * Add a new card_voters
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  int $list_id Selected list ID (required)
     * @param  int $card_id Selected card ID (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPostWithHttpInfo($token, $board_id, $list_id, $card_id)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPostRequest($token, $board_id, $list_id, $card_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPostAsync
     *
     * Add a new card_voters
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  int $list_id Selected list ID (required)
     * @param  int $card_id Selected card ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPostAsync($token, $board_id, $list_id, $card_id)
    {
        return $this->v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPostAsyncWithHttpInfo($token, $board_id, $list_id, $card_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPostAsyncWithHttpInfo
     *
     * Add a new card_voters
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  int $list_id Selected list ID (required)
     * @param  int $card_id Selected card ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPostAsyncWithHttpInfo($token, $board_id, $list_id, $card_id)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPostRequest($token, $board_id, $list_id, $card_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPost'
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  int $list_id Selected list ID (required)
     * @param  int $card_id Selected card ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPostRequest($token, $board_id, $list_id, $card_id)
    {
        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPost'
            );
        }
        // verify the required parameter 'board_id' is set
        if ($board_id === null || (is_array($board_id) && count($board_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $board_id when calling v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPost'
            );
        }
        // verify the required parameter 'list_id' is set
        if ($list_id === null || (is_array($list_id) && count($list_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $list_id when calling v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPost'
            );
        }
        // verify the required parameter 'card_id' is set
        if ($card_id === null || (is_array($card_id) && count($card_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $card_id when calling v1BoardsBoardIdListsListIdCardsCardIdCardVotersJsonPost'
            );
        }

        $resourcePath = '/v1/boards/{boardId}/lists/{listId}/cards/{cardId}/card_voters.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($token !== null) {
            $queryParams['token'] = ObjectSerializer::toQueryValue($token);
        }

        // path params
        if ($board_id !== null) {
            $resourcePath = str_replace(
                '{' . 'boardId' . '}',
                ObjectSerializer::toPathValue($board_id),
                $resourcePath
            );
        }
        // path params
        if ($list_id !== null) {
            $resourcePath = str_replace(
                '{' . 'listId' . '}',
                ObjectSerializer::toPathValue($list_id),
                $resourcePath
            );
        }
        // path params
        if ($card_id !== null) {
            $resourcePath = str_replace(
                '{' . 'cardId' . '}',
                ObjectSerializer::toPathValue($card_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
