<?php
/**
 * ListsApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RestyaBoard
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * ListsApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ListsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1BoardsBoardIdListsJsonDelete
     *
     * Deletes a list
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to delete (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function v1BoardsBoardIdListsJsonDelete($token, $board_id)
    {
        list($response) = $this->v1BoardsBoardIdListsJsonDeleteWithHttpInfo($token, $board_id);
        return $response;
    }

    /**
     * Operation v1BoardsBoardIdListsJsonDeleteWithHttpInfo
     *
     * Deletes a list
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to delete (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1BoardsBoardIdListsJsonDeleteWithHttpInfo($token, $board_id)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsJsonDeleteRequest($token, $board_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1BoardsBoardIdListsJsonDeleteAsync
     *
     * Deletes a list
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to delete (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsJsonDeleteAsync($token, $board_id)
    {
        return $this->v1BoardsBoardIdListsJsonDeleteAsyncWithHttpInfo($token, $board_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1BoardsBoardIdListsJsonDeleteAsyncWithHttpInfo
     *
     * Deletes a list
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to delete (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsJsonDeleteAsyncWithHttpInfo($token, $board_id)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsJsonDeleteRequest($token, $board_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1BoardsBoardIdListsJsonDelete'
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to delete (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1BoardsBoardIdListsJsonDeleteRequest($token, $board_id)
    {
        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling v1BoardsBoardIdListsJsonDelete'
            );
        }
        // verify the required parameter 'board_id' is set
        if ($board_id === null || (is_array($board_id) && count($board_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $board_id when calling v1BoardsBoardIdListsJsonDelete'
            );
        }

        $resourcePath = '/v1/boards/{boardId}/lists.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($token !== null) {
            $queryParams['token'] = ObjectSerializer::toQueryValue($token);
        }

        // path params
        if ($board_id !== null) {
            $resourcePath = str_replace(
                '{' . 'boardId' . '}',
                ObjectSerializer::toPathValue($board_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/xml', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/xml', 'application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1BoardsBoardIdListsJsonGet
     *
     * View board by ID
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function v1BoardsBoardIdListsJsonGet($token, $board_id)
    {
        list($response) = $this->v1BoardsBoardIdListsJsonGetWithHttpInfo($token, $board_id);
        return $response;
    }

    /**
     * Operation v1BoardsBoardIdListsJsonGetWithHttpInfo
     *
     * View board by ID
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1BoardsBoardIdListsJsonGetWithHttpInfo($token, $board_id)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsJsonGetRequest($token, $board_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1BoardsBoardIdListsJsonGetAsync
     *
     * View board by ID
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsJsonGetAsync($token, $board_id)
    {
        return $this->v1BoardsBoardIdListsJsonGetAsyncWithHttpInfo($token, $board_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1BoardsBoardIdListsJsonGetAsyncWithHttpInfo
     *
     * View board by ID
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsJsonGetAsyncWithHttpInfo($token, $board_id)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsJsonGetRequest($token, $board_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1BoardsBoardIdListsJsonGet'
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1BoardsBoardIdListsJsonGetRequest($token, $board_id)
    {
        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling v1BoardsBoardIdListsJsonGet'
            );
        }
        // verify the required parameter 'board_id' is set
        if ($board_id === null || (is_array($board_id) && count($board_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $board_id when calling v1BoardsBoardIdListsJsonGet'
            );
        }

        $resourcePath = '/v1/boards/{boardId}/lists.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($token !== null) {
            $queryParams['token'] = ObjectSerializer::toQueryValue($token);
        }

        // path params
        if ($board_id !== null) {
            $resourcePath = str_replace(
                '{' . 'boardId' . '}',
                ObjectSerializer::toPathValue($board_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/xml', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/xml', 'application/json'],
                ['application/json', 'application/xml']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1BoardsBoardIdListsJsonPost
     *
     * Add a new list to the board
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  \Swagger\Client\Model\Body9 $body Created list object (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function v1BoardsBoardIdListsJsonPost($token, $board_id, $body)
    {
        list($response) = $this->v1BoardsBoardIdListsJsonPostWithHttpInfo($token, $board_id, $body);
        return $response;
    }

    /**
     * Operation v1BoardsBoardIdListsJsonPostWithHttpInfo
     *
     * Add a new list to the board
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  \Swagger\Client\Model\Body9 $body Created list object (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1BoardsBoardIdListsJsonPostWithHttpInfo($token, $board_id, $body)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsJsonPostRequest($token, $board_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1BoardsBoardIdListsJsonPostAsync
     *
     * Add a new list to the board
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  \Swagger\Client\Model\Body9 $body Created list object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsJsonPostAsync($token, $board_id, $body)
    {
        return $this->v1BoardsBoardIdListsJsonPostAsyncWithHttpInfo($token, $board_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1BoardsBoardIdListsJsonPostAsyncWithHttpInfo
     *
     * Add a new list to the board
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  \Swagger\Client\Model\Body9 $body Created list object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsJsonPostAsyncWithHttpInfo($token, $board_id, $body)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsJsonPostRequest($token, $board_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1BoardsBoardIdListsJsonPost'
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  \Swagger\Client\Model\Body9 $body Created list object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1BoardsBoardIdListsJsonPostRequest($token, $board_id, $body)
    {
        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling v1BoardsBoardIdListsJsonPost'
            );
        }
        // verify the required parameter 'board_id' is set
        if ($board_id === null || (is_array($board_id) && count($board_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $board_id when calling v1BoardsBoardIdListsJsonPost'
            );
        }
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling v1BoardsBoardIdListsJsonPost'
            );
        }

        $resourcePath = '/v1/boards/{boardId}/lists.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($token !== null) {
            $queryParams['token'] = ObjectSerializer::toQueryValue($token);
        }

        // path params
        if ($board_id !== null) {
            $resourcePath = str_replace(
                '{' . 'boardId' . '}',
                ObjectSerializer::toPathValue($board_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/xml', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/xml', 'application/json'],
                ['application/json', 'application/xml']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1BoardsBoardIdListsListIdActivitiesJsonGet
     *
     * Activities
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  int $list_id Selected list ID (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function v1BoardsBoardIdListsListIdActivitiesJsonGet($token, $board_id, $list_id)
    {
        list($response) = $this->v1BoardsBoardIdListsListIdActivitiesJsonGetWithHttpInfo($token, $board_id, $list_id);
        return $response;
    }

    /**
     * Operation v1BoardsBoardIdListsListIdActivitiesJsonGetWithHttpInfo
     *
     * Activities
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  int $list_id Selected list ID (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1BoardsBoardIdListsListIdActivitiesJsonGetWithHttpInfo($token, $board_id, $list_id)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsListIdActivitiesJsonGetRequest($token, $board_id, $list_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1BoardsBoardIdListsListIdActivitiesJsonGetAsync
     *
     * Activities
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  int $list_id Selected list ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsListIdActivitiesJsonGetAsync($token, $board_id, $list_id)
    {
        return $this->v1BoardsBoardIdListsListIdActivitiesJsonGetAsyncWithHttpInfo($token, $board_id, $list_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1BoardsBoardIdListsListIdActivitiesJsonGetAsyncWithHttpInfo
     *
     * Activities
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  int $list_id Selected list ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsListIdActivitiesJsonGetAsyncWithHttpInfo($token, $board_id, $list_id)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsListIdActivitiesJsonGetRequest($token, $board_id, $list_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1BoardsBoardIdListsListIdActivitiesJsonGet'
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  int $list_id Selected list ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1BoardsBoardIdListsListIdActivitiesJsonGetRequest($token, $board_id, $list_id)
    {
        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling v1BoardsBoardIdListsListIdActivitiesJsonGet'
            );
        }
        // verify the required parameter 'board_id' is set
        if ($board_id === null || (is_array($board_id) && count($board_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $board_id when calling v1BoardsBoardIdListsListIdActivitiesJsonGet'
            );
        }
        // verify the required parameter 'list_id' is set
        if ($list_id === null || (is_array($list_id) && count($list_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $list_id when calling v1BoardsBoardIdListsListIdActivitiesJsonGet'
            );
        }

        $resourcePath = '/v1/boards/{boardId}/lists/{listId}/activities.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($token !== null) {
            $queryParams['token'] = ObjectSerializer::toQueryValue($token);
        }

        // path params
        if ($board_id !== null) {
            $resourcePath = str_replace(
                '{' . 'boardId' . '}',
                ObjectSerializer::toPathValue($board_id),
                $resourcePath
            );
        }
        // path params
        if ($list_id !== null) {
            $resourcePath = str_replace(
                '{' . 'listId' . '}',
                ObjectSerializer::toPathValue($list_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1BoardsBoardIdListsListIdJsonDelete
     *
     * Deletes a list
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to delete (required)
     * @param  int $list_id list id to delete (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function v1BoardsBoardIdListsListIdJsonDelete($token, $board_id, $list_id)
    {
        list($response) = $this->v1BoardsBoardIdListsListIdJsonDeleteWithHttpInfo($token, $board_id, $list_id);
        return $response;
    }

    /**
     * Operation v1BoardsBoardIdListsListIdJsonDeleteWithHttpInfo
     *
     * Deletes a list
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to delete (required)
     * @param  int $list_id list id to delete (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1BoardsBoardIdListsListIdJsonDeleteWithHttpInfo($token, $board_id, $list_id)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsListIdJsonDeleteRequest($token, $board_id, $list_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1BoardsBoardIdListsListIdJsonDeleteAsync
     *
     * Deletes a list
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to delete (required)
     * @param  int $list_id list id to delete (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsListIdJsonDeleteAsync($token, $board_id, $list_id)
    {
        return $this->v1BoardsBoardIdListsListIdJsonDeleteAsyncWithHttpInfo($token, $board_id, $list_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1BoardsBoardIdListsListIdJsonDeleteAsyncWithHttpInfo
     *
     * Deletes a list
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to delete (required)
     * @param  int $list_id list id to delete (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsListIdJsonDeleteAsyncWithHttpInfo($token, $board_id, $list_id)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsListIdJsonDeleteRequest($token, $board_id, $list_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1BoardsBoardIdListsListIdJsonDelete'
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to delete (required)
     * @param  int $list_id list id to delete (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1BoardsBoardIdListsListIdJsonDeleteRequest($token, $board_id, $list_id)
    {
        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling v1BoardsBoardIdListsListIdJsonDelete'
            );
        }
        // verify the required parameter 'board_id' is set
        if ($board_id === null || (is_array($board_id) && count($board_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $board_id when calling v1BoardsBoardIdListsListIdJsonDelete'
            );
        }
        // verify the required parameter 'list_id' is set
        if ($list_id === null || (is_array($list_id) && count($list_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $list_id when calling v1BoardsBoardIdListsListIdJsonDelete'
            );
        }

        $resourcePath = '/v1/boards/{boardId}/lists/{listId}.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($token !== null) {
            $queryParams['token'] = ObjectSerializer::toQueryValue($token);
        }

        // path params
        if ($board_id !== null) {
            $resourcePath = str_replace(
                '{' . 'boardId' . '}',
                ObjectSerializer::toPathValue($board_id),
                $resourcePath
            );
        }
        // path params
        if ($list_id !== null) {
            $resourcePath = str_replace(
                '{' . 'listId' . '}',
                ObjectSerializer::toPathValue($list_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/xml', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/xml', 'application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1BoardsBoardIdListsListIdJsonPut
     *
     * Update an existing webhooks
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to update (required)
     * @param  int $list_id list id to update (required)
     * @param  \Swagger\Client\Model\Body39 $body Update list object (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function v1BoardsBoardIdListsListIdJsonPut($token, $board_id, $list_id, $body)
    {
        $this->v1BoardsBoardIdListsListIdJsonPutWithHttpInfo($token, $board_id, $list_id, $body);
    }

    /**
     * Operation v1BoardsBoardIdListsListIdJsonPutWithHttpInfo
     *
     * Update an existing webhooks
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to update (required)
     * @param  int $list_id list id to update (required)
     * @param  \Swagger\Client\Model\Body39 $body Update list object (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1BoardsBoardIdListsListIdJsonPutWithHttpInfo($token, $board_id, $list_id, $body)
    {
        $returnType = '';
        $request = $this->v1BoardsBoardIdListsListIdJsonPutRequest($token, $board_id, $list_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation v1BoardsBoardIdListsListIdJsonPutAsync
     *
     * Update an existing webhooks
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to update (required)
     * @param  int $list_id list id to update (required)
     * @param  \Swagger\Client\Model\Body39 $body Update list object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsListIdJsonPutAsync($token, $board_id, $list_id, $body)
    {
        return $this->v1BoardsBoardIdListsListIdJsonPutAsyncWithHttpInfo($token, $board_id, $list_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1BoardsBoardIdListsListIdJsonPutAsyncWithHttpInfo
     *
     * Update an existing webhooks
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to update (required)
     * @param  int $list_id list id to update (required)
     * @param  \Swagger\Client\Model\Body39 $body Update list object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsListIdJsonPutAsyncWithHttpInfo($token, $board_id, $list_id, $body)
    {
        $returnType = '';
        $request = $this->v1BoardsBoardIdListsListIdJsonPutRequest($token, $board_id, $list_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1BoardsBoardIdListsListIdJsonPut'
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to update (required)
     * @param  int $list_id list id to update (required)
     * @param  \Swagger\Client\Model\Body39 $body Update list object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1BoardsBoardIdListsListIdJsonPutRequest($token, $board_id, $list_id, $body)
    {
        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling v1BoardsBoardIdListsListIdJsonPut'
            );
        }
        // verify the required parameter 'board_id' is set
        if ($board_id === null || (is_array($board_id) && count($board_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $board_id when calling v1BoardsBoardIdListsListIdJsonPut'
            );
        }
        // verify the required parameter 'list_id' is set
        if ($list_id === null || (is_array($list_id) && count($list_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $list_id when calling v1BoardsBoardIdListsListIdJsonPut'
            );
        }
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling v1BoardsBoardIdListsListIdJsonPut'
            );
        }

        $resourcePath = '/v1/boards/{boardId}/lists/{listId}.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($token !== null) {
            $queryParams['token'] = ObjectSerializer::toQueryValue($token);
        }

        // path params
        if ($board_id !== null) {
            $resourcePath = str_replace(
                '{' . 'boardId' . '}',
                ObjectSerializer::toPathValue($board_id),
                $resourcePath
            );
        }
        // path params
        if ($list_id !== null) {
            $resourcePath = str_replace(
                '{' . 'listId' . '}',
                ObjectSerializer::toPathValue($list_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1BoardsBoardIdListsListIdListSubscribersJsonPost
     *
     * Add a new list subcriber to the board
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  int $list_id Selected list ID (required)
     * @param  \Swagger\Client\Model\Body26 $body Created list subcriber object (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function v1BoardsBoardIdListsListIdListSubscribersJsonPost($token, $board_id, $list_id, $body)
    {
        list($response) = $this->v1BoardsBoardIdListsListIdListSubscribersJsonPostWithHttpInfo($token, $board_id, $list_id, $body);
        return $response;
    }

    /**
     * Operation v1BoardsBoardIdListsListIdListSubscribersJsonPostWithHttpInfo
     *
     * Add a new list subcriber to the board
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  int $list_id Selected list ID (required)
     * @param  \Swagger\Client\Model\Body26 $body Created list subcriber object (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1BoardsBoardIdListsListIdListSubscribersJsonPostWithHttpInfo($token, $board_id, $list_id, $body)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsListIdListSubscribersJsonPostRequest($token, $board_id, $list_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1BoardsBoardIdListsListIdListSubscribersJsonPostAsync
     *
     * Add a new list subcriber to the board
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  int $list_id Selected list ID (required)
     * @param  \Swagger\Client\Model\Body26 $body Created list subcriber object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsListIdListSubscribersJsonPostAsync($token, $board_id, $list_id, $body)
    {
        return $this->v1BoardsBoardIdListsListIdListSubscribersJsonPostAsyncWithHttpInfo($token, $board_id, $list_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1BoardsBoardIdListsListIdListSubscribersJsonPostAsyncWithHttpInfo
     *
     * Add a new list subcriber to the board
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  int $list_id Selected list ID (required)
     * @param  \Swagger\Client\Model\Body26 $body Created list subcriber object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsListIdListSubscribersJsonPostAsyncWithHttpInfo($token, $board_id, $list_id, $body)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsListIdListSubscribersJsonPostRequest($token, $board_id, $list_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1BoardsBoardIdListsListIdListSubscribersJsonPost'
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id Selected board ID (required)
     * @param  int $list_id Selected list ID (required)
     * @param  \Swagger\Client\Model\Body26 $body Created list subcriber object (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1BoardsBoardIdListsListIdListSubscribersJsonPostRequest($token, $board_id, $list_id, $body)
    {
        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling v1BoardsBoardIdListsListIdListSubscribersJsonPost'
            );
        }
        // verify the required parameter 'board_id' is set
        if ($board_id === null || (is_array($board_id) && count($board_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $board_id when calling v1BoardsBoardIdListsListIdListSubscribersJsonPost'
            );
        }
        // verify the required parameter 'list_id' is set
        if ($list_id === null || (is_array($list_id) && count($list_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $list_id when calling v1BoardsBoardIdListsListIdListSubscribersJsonPost'
            );
        }
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling v1BoardsBoardIdListsListIdListSubscribersJsonPost'
            );
        }

        $resourcePath = '/v1/boards/{boardId}/lists/{listId}/list_subscribers.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($token !== null) {
            $queryParams['token'] = ObjectSerializer::toQueryValue($token);
        }

        // path params
        if ($board_id !== null) {
            $resourcePath = str_replace(
                '{' . 'boardId' . '}',
                ObjectSerializer::toPathValue($board_id),
                $resourcePath
            );
        }
        // path params
        if ($list_id !== null) {
            $resourcePath = str_replace(
                '{' . 'listId' . '}',
                ObjectSerializer::toPathValue($list_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/xml', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/xml', 'application/json'],
                ['application/json', 'application/xml']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPut
     *
     * Update an existing webhooks
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to update (required)
     * @param  int $list_id list id to update (required)
     * @param  int $list_subscriber_id listSubscriber Id to update (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPut($token, $board_id, $list_id, $list_subscriber_id)
    {
        list($response) = $this->v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPutWithHttpInfo($token, $board_id, $list_id, $list_subscriber_id);
        return $response;
    }

    /**
     * Operation v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPutWithHttpInfo
     *
     * Update an existing webhooks
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to update (required)
     * @param  int $list_id list id to update (required)
     * @param  int $list_subscriber_id listSubscriber Id to update (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPutWithHttpInfo($token, $board_id, $list_id, $list_subscriber_id)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPutRequest($token, $board_id, $list_id, $list_subscriber_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPutAsync
     *
     * Update an existing webhooks
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to update (required)
     * @param  int $list_id list id to update (required)
     * @param  int $list_subscriber_id listSubscriber Id to update (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPutAsync($token, $board_id, $list_id, $list_subscriber_id)
    {
        return $this->v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPutAsyncWithHttpInfo($token, $board_id, $list_id, $list_subscriber_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPutAsyncWithHttpInfo
     *
     * Update an existing webhooks
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to update (required)
     * @param  int $list_id list id to update (required)
     * @param  int $list_subscriber_id listSubscriber Id to update (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPutAsyncWithHttpInfo($token, $board_id, $list_id, $list_subscriber_id)
    {
        $returnType = 'object';
        $request = $this->v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPutRequest($token, $board_id, $list_id, $list_subscriber_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPut'
     *
     * @param  string $token OAuth token (required)
     * @param  int $board_id board id to update (required)
     * @param  int $list_id list id to update (required)
     * @param  int $list_subscriber_id listSubscriber Id to update (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPutRequest($token, $board_id, $list_id, $list_subscriber_id)
    {
        // verify the required parameter 'token' is set
        if ($token === null || (is_array($token) && count($token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token when calling v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPut'
            );
        }
        // verify the required parameter 'board_id' is set
        if ($board_id === null || (is_array($board_id) && count($board_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $board_id when calling v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPut'
            );
        }
        // verify the required parameter 'list_id' is set
        if ($list_id === null || (is_array($list_id) && count($list_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $list_id when calling v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPut'
            );
        }
        // verify the required parameter 'list_subscriber_id' is set
        if ($list_subscriber_id === null || (is_array($list_subscriber_id) && count($list_subscriber_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $list_subscriber_id when calling v1BoardsBoardIdListsListIdListSubscribersListSubscriberIdJsonPut'
            );
        }

        $resourcePath = '/v1/boards/{boardId}/lists/{listId}/list_subscribers/{listSubscriberId}.json';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($token !== null) {
            $queryParams['token'] = ObjectSerializer::toQueryValue($token);
        }

        // path params
        if ($board_id !== null) {
            $resourcePath = str_replace(
                '{' . 'boardId' . '}',
                ObjectSerializer::toPathValue($board_id),
                $resourcePath
            );
        }
        // path params
        if ($list_id !== null) {
            $resourcePath = str_replace(
                '{' . 'listId' . '}',
                ObjectSerializer::toPathValue($list_id),
                $resourcePath
            );
        }
        // path params
        if ($list_subscriber_id !== null) {
            $resourcePath = str_replace(
                '{' . 'listSubscriberId' . '}',
                ObjectSerializer::toPathValue($list_subscriber_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
